### ISSUE TITLE
How to fix 'Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only' error in windows server 2019 with DockerProvider service

### ISSUE THREAD

**Issue by dborzouei** [microsoft/Docker-Provider#229]
I'm installed docker in windows server 2019 with ``DockerProvider``
I'm using this code 
```
Install-Module DockerProvider
Install-Package Docker -ProviderName DockerProvider -RequiredVersion preview
[Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
```
after that I install ``Docker-Compose`` with this code 
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-WebRequest "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Windows-x86_64.exe" -UseBasicParsing -OutFile $Env:ProgramFiles\Docker\docker-compose.exe
```

after that I use a docker compose file 
```
version: "3.5"

services:


  rabbitmq:
    # restart: always
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - myname
    # network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

 

networks:
  myname:
    name: myname-network

volumes:
  rabbitmq:
    driver: local
```
everything is Ok up to here
but after i call ``http://localhost:15672/`` url in my browser
rabbitmq crashes and I see this error in ``docker logs <container-id>``
```
Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only
```
this ``.yml`` file is working correctly in ``docker for windows``
but after running the file in windows server, I see this error

**Comment by changhuixu** [comment]
volumes: 
      - rabbitmq:/var/lib/rabbitmq
------------------------------------->
need to map your volume to `/var/lib/rabbitmq/mnesia` instead.

**Comment by ElenaShlykova** [comment]
Same issue, but I do not use volume in my yaml:

```
version: "3.7"

services:
    rabbit-mq:
        image: rabbitmq:3.7-management
        container_name: rabbit-mq
        environment:
            - RABBITMQ_DEFAULT_USER=devtools_user
            - RABBITMQ_DEFAULT_PASS=DevTools1!
        ports:
            - "15672:15672"
            - "5672:5672"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
```
